apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-mongo
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-mongo
  template:
    metadata:
      labels:
        app: fastfood-mongo
    spec:
      containers:
        - name: fastfood-mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-mongo
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-mongo
                  key: mongo-root-password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: fastfood-mongo
        - name: mongo-init
          configMap:
            name: fastfood-mongo