name: pipeline-api-dotnet

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dotnet_build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
  
  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: dotnet_build
    environment: prd

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud - Begin analysis
        run: |
          dotnet-sonarscanner begin \
            /k:"fiap-soat-projects_fiap-soat-fastfood" \
            /o:"fiap-soat-projects" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io"
            

      - name: Build
        run: dotnet build --no-incremental

      - name: SonarCloud - End analysis
        run: |
          dotnet-sonarscanner end \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  build_push_image:
    runs-on: ubuntu-latest
    needs: sonarqube-analysis
    environment: prd

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Create image tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            VERSION="pr-${{ github.event.pull_request.number }}"
          else
            VERSION="latest"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build&Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_TENANT }}/fiap-soat-fastfood-api:${{ steps.vars.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image
    environment: prd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Settings
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      - name: Install kubectl and kubelogin
        run: |
          az aks install-cli
          kubelogin --version

      - name: Get AKS Kubeconfig
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Convert Kubeconfig for SPN
        run: |
          kubelogin convert-kubeconfig \
            -l spn \
            --client-id "${{ secrets.AZURE_CLIENT_ID }}" \
            --client-secret "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant-id "${{ secrets.AZURE_TENANT_ID }}"

      - name: Create secrets manifest
        run: |
          cat > ./k8s/fastfood-api-secret.yaml <<'EOF'
          ${{ secrets.API_SECRETS_MANIFEST }}
          EOF

      - name: Create image tag
        if: github.event_name == 'pull_request'
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            VERSION="pr-${{ github.event.pull_request.number }}"
          else
            VERSION="latest"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install yq
        if: github.event_name == 'pull_request'
        uses: mikefarah/yq@v4

      - name: Update image tag using yq
        if: github.event_name == 'pull_request'
        run: |
          yq e ".spec.template.spec.containers[0].image = \"ajjposproj/fiap-soat-fastfood-api:${{ env.VERSION }}\"" -i k8s/fastfood-api-deployment.yaml

      - name: Deploy
        run: |
          kubectl apply -f k8s/.
          kubectl rollout status deployment/fastfood-api -n fiap --timeout=60s
